# fly.toml file generated for protohacker-py on 2023-01-16T10:11:25Z

app = "protohacker-py"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  TCP_PORT = "8080"
  UDP_PORT = "5000"
  DEBUG = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1100
    soft_limit = 750

  [[services.ports]]
    port = "10001"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
